CREATE TABLE supersale (
    Row_ID NUMBER,
    Order_ID VARCHAR2(50),
    Order_Date DATE,
    Ship_Date DATE,
    Ship_Mode VARCHAR2(50),
    Customer_ID VARCHAR2(50),
    Customer_Name VARCHAR2(100),
    Segment VARCHAR2(50),
    Country VARCHAR2(50),
    City VARCHAR2(50),
    State VARCHAR2(50),
    Postal_Code NUMBER,
    Region VARCHAR2(50),
    Product_ID VARCHAR2(50),
    Category VARCHAR2(50),
    Sub_Category VARCHAR2(50),
    Product_Name VARCHAR2(255),
    Sales NUMBER(10,2),
    Quantity NUMBER,
    Discount NUMBER(5,2),
    Profit NUMBER(10,2)
);

select *from supersale;

select sales
from supersale
where rownum <=10;

--TOTAL SALES:

Business Meaning

Measures total company revenue generated from all orders.

Interview Explanation

“I used the SUM() aggregate function to calculate overall revenue generated by the business.”

SELECT SUM(SALES) AS TOTAL_SALES
FROM SUPERSALE;

--TOTAL PROFIT

Business Meaning

Shows actual earnings after costs.

Important Insight

Profit is much lower than sales

This may indicate:

high discounts
operational costs
low profit margins

SELECT SUM(PROFIT) AS TOTAL_PROFIT
FROM SUPERSALE;

--TOTAL ORDERS:

business meaning:

Represents total business transactions/orders processed.

SELECT COUNT(*) AS TOTAL_ORDERS
FROM SUPERSALE;


--QUERY 1: TOP SELLING PRODUCTS:

SELECT *
FROM(

SELECT PRODUCT_NAME,
        SUM(SALES)AS REVENUE
        FROM SUPERSALE
GROUP BY PRODUCT_NAME
ORDER BY REVENUE DESC
)
WHERE ROWNUM<=10;

--QUERY 2:REGION WISE SALES ANALYSIS:

SELECT REGION,SUM(SALES)AS TOTAL_SALES
FROM SUPERSALE
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;

--QUERY 3:CATEGORY_WISE SALES

SELECT CATEGORY,SUM(SALES)AS TOTAL_SALES
FROM SUPERSALE
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC;

--QUERY 4:MONTHLY SALES TREND ANALYSIS:

SELECT EXTRACT(MONTH FROM ORDER_DATE)AS MONTH,
SUM(SALES) AS MONTHLY_SALES
FROM SUPERSALE
GROUP BY EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY MONTH;

--QUERY 5:TOP PROFITABLE PRODUCTS:

SELECT *
FROM(
     SELECT PRODUCT_NAME,
     SUM(PROFIT) AS TOTAL_PROFIT
     FROM SUPERSALE
     GROUP BY PRODUCT_NAME
     ORDER BY TOTAL_PROFIT DESC
)
WHERE ROWNUM <=10;

--QUERY 6 PROFIT ANALYSIS BY CATEGORY

Earlier we analyzed:

category-wise sales

Now we analyze:

category-wise profit

This is more important for businesses.

Because:

High sales ? High profit

SELECT CATEGORY,
SUM(PROFIT) AS TOTAL_PROFIT
FROM SUPERSALE
GROUP BY CATEGORY
ORDER BY TOTAL_PROFIT DESC;

--QUERY 6 CUSTOMER ANALYSIS:

Business Meaning

This helps company identify:

VIP customers
high-value buyers
customers contributing most revenue

SELECT *
FROM(
  SELECT CUSTOMER_NAME,
  SUM(SALES) AS TOTAL_SALES
  FROM SUPERSALE
  GROUP BY CUSTOMER_NAME
  ORDER BY TOTAL_SALES DESC
)
WHERE ROWNUM <=10;

--QUERY 7 OVERALL PROFIT MARGIN ANALYSIS:

FORMULA PROFIT MARGIN=PROFIT/SALES *100

SELECT 
  ROUND((SUM(PROFIT)/SUM(SALES))*100,2)AS PROFIT_MARGIN_PERCENTAGE
FROM SUPERSALE;

--QUERY 8 MOST PROFITABLE REGION WISE:

Most Profitable Regions

Earlier:

we analyzed region-wise sales

Now:

we analyze region-wise profit

This is more important for business decisions.

SELECT REGION,SUM(PROFIT) AS TOTAL_PROFIT
FROM SUPERSALE
GROUP BY REGION
ORDER BY TOTAL_PROFIT DESC;

--QUERY 9 REGION-WISE SALES VS PROFIT:

SELECT REGION,
      SUM(SALES) AS TOTAL_SALES,
      SUM(PROFIT) AS TOTAL_PROFIT
FROM SUPERSALE
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;

-- QUERY 10 MONTHLY PROFIT TREND ANALYSIS:

This helps analyze:

seasonal profitability
profitable months
weak-performing periods

SELECT EXTRACT(MONTH FROM ORDER_DATE)AS MONTH,
SUM(PROFIT) AS TOTAL_PROFIT
FROM SUPERSALE
GROUP BY EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY TOTAL_PROFIT DESC;

--QUERY 11 ADVANCED BUSINESS ANALYSIS:

Until now:

we analyzed totals
regions
categories
customers
monthly trends

Now we’ll analyze:

Discount Impact on Profit

This is a very realistic business problem.

Companies often ask:

“Are discounts reducing our profits?” 

SELECT 
     ROUND(AVG(DISCOUNT)*100,2)AS AVG_DISCOUNT_PERCENTAGE,
     ROUND(AVG(PROFIT),2) AS AVG_PROFIT
    FROM SUPERSALE;

Final SQL Analysis Step:

Profit Margin by Category 

This combines:

sales
profit
business efficiency

This is one of the most professional-looking analyses.

SELECT CATEGORY,
     SUM(SALES) AS TOTAL_SALES,
     SUM(PROFIT) AS TOTAL_PROFIT,
     ROUND((SUM(PROFIT)/SUM(SALES))*100,2)AS PROFIT_MARGIN_PERCENTAGE
FROM SUPERSALE
GROUP BY CATEGORY
ORDER BY PROFIT_MARGIN_PERCENTAGE DESC;

SELECT *FROM SUPERSALE;
